window.BEST_SOUND_DATA = {
  defaultLang: "ru",
  contacts: {
    emailUser: "BESTJU",
    emailDomain: "YANDEX.RU"
  },
  i18n: {
    ru: {
      navConcerts: "Концерты",
      navGallery: "Фотогалерея",
      navVideo: "Видео",
      navContacts: "Контакты",
      heroKicker: "CONCERT AGENCY \"BEST SOUND\"",
      heroTitle: "Наши концерты — произведение искусства.",
      heroText: "Концертное агентство BEST SOUND. Концерты, фотогалерея, видео и контакты.",
      heroPrimary: "Запросить артиста",
      heroSecondary: "Смотреть концерты",
      eventsTitle: "Концерты",
      eventsText: "Опубликованные артисты и даты.",
      searchLabel: "Поиск",
      searchPlaceholder: "Артист, город, страна...",
      all: "Все",
      galleryTitle: "Фотогалерея",
      galleryText: "Фото с концертов BEST SOUND.",
      videoTitle: "Видео",
      videoText: "Выбирайте, какой концерт вам бы хотелось посетить.",
      reputationTitle: "BEST REPUTATION",
      contactsTitle: "Контакты",
      requestTitle: "Make a request",
      name: "Имя",
      email: "Email",
      phone: "Телефон",
      request: "Запрос",
      send: "Отправить",
      modalButton: "Оставить заявку",
      emptyTitle: "Ничего не найдено",
      emptyText: "Измените фильтр или поиск.",
      mailSubject: "Заявка с сайта BEST SOUND",
      toastTitle: "Письмо подготовлено",
      toastText: "Проверьте текст и отправьте письмо.",
      privacy: "Политика обработки данных"
    },
    en: {
      navConcerts: "Concerts",
      navGallery: "Photo Gallery",
      navVideo: "Video",
      navContacts: "Contacts",
      heroKicker: "CONCERT AGENCY \"BEST SOUND\"",
      heroTitle: "Our concerts are works of art.",
      heroText: "BEST SOUND concert agency. Concerts, photo gallery, video and contacts.",
      heroPrimary: "Request artists",
      heroSecondary: "View concerts",
      eventsTitle: "Concerts",
      eventsText: "Published artists and dates.",
      searchLabel: "Search",
      searchPlaceholder: "Artist, city, country...",
      all: "All",
      galleryTitle: "Photo Gallery",
      galleryText: "Photos from BEST SOUND concerts.",
      videoTitle: "Video",
      videoText: "Choose which concert you would like to attend.",
      reputationTitle: "BEST REPUTATION",
      contactsTitle: "Contacts",
      requestTitle: "Make a request",
      name: "Name",
      email: "Email",
      phone: "Tel",
      request: "Request",
      send: "Send",
      modalButton: "Make a request",
      emptyTitle: "Nothing found",
      emptyText: "Change filter or search query.",
      mailSubject: "Request from BEST SOUND website",
      toastTitle: "Email prepared",
      toastText: "Check the text and send it.",
      privacy: "Privacy policy"
    },
    it: {
      navConcerts: "Concerti",
      navGallery: "Galleria foto",
      navVideo: "Video",
      navContacts: "Contatti",
      heroKicker: "AGENZIA DI CONCERTI \"BEST SOUND\"",
      heroTitle: "I nostri concerti sono opere d’arte.",
      heroText: "Agenzia di concerti BEST SOUND. Concerti, galleria foto, video e contatti.",
      heroPrimary: "Richiedi artisti",
      heroSecondary: "Vedi concerti",
      eventsTitle: "Concerti",
      eventsText: "Artisti e date pubblicati.",
      searchLabel: "Cerca",
      searchPlaceholder: "Artista, città, paese...",
      all: "Tutti",
      galleryTitle: "Galleria foto",
      galleryText: "Foto dai concerti BEST SOUND.",
      videoTitle: "Video",
      videoText: "Scegli quale concerto vorresti visitare.",
      reputationTitle: "BEST REPUTATION",
      contactsTitle: "Contatti",
      requestTitle: "Invia una richiesta",
      name: "Nome",
      email: "Email",
      phone: "Tel",
      request: "Richiesta",
      send: "Invia",
      modalButton: "Invia una richiesta",
      emptyTitle: "Nessun risultato",
      emptyText: "Cambia filtro o ricerca.",
      mailSubject: "Richiesta dal sito BEST SOUND",
      toastTitle: "Email preparata",
      toastText: "Controlla il testo e invialo.",
      privacy: "Informativa privacy"
    }
  },
  benefits: [
    "BEST REPUTATION",
    "OVER 20 YEARS OF EXPERIENCE",
    "HUNDREDS OF SUCCESSFUL EVENTS",
    "THOUSANDS OF SATISFIED VIEWERS",
    "COOPERATION WITH WORLD STARS",
    "WIDE GEOGRAPHY OF CONCERTS"
  ],
  filters: [
    { id: "all", label: "All" },
    { id: "safina", label: "Alessandro Safina" },
    { id: "turner", label: "Joe Lynn Turner" },
    { id: "paciotti", label: "Federico Paciotti" }
  ],
  tours: [
    {
      id: "safina-2026",
      category: "safina",
      title: "ALESSANDRO SAFINA",
      subtitle: "Famous Italian tenor with big orchestra",
      dates: [
        "FEBRUARY 21, 2026 — TASHKENT, UZBEKISTAN",
        "FEBRUARY 24, 2026 — BISHKEK, KYRGYZSTAN",
        "FEBRUARY 26, 2026 — MINSK, BELARUS",
        "FEBRUARY 28, 2026 — KALININGRAD, RUSSIA",
        "MARCH 02, 2026 — SAINT PETERSBURG, RUSSIA",
        "MARCH 04, 2026 — MOSCOW, RUSSIA",
        "MARCH 08, 2026 — CHELYABINSK, RUSSIA",
        "MARCH 10, 2026 — UFA, RUSSIA",
        "MARCH 12, 2026 — EKATERINBURG, RUSSIA",
        "MARCH 14, 2026 — SAMARA, RUSSIA",
        "MARCH 16, 2026 — NOVOSIBIRSK, RUSSIA",
        "MARCH 18, 2026 — OMSK, RUSSIA"
      ]
    },
    {
      id: "safina-2025",
      category: "safina",
      title: "ALESSANDRO SAFINA",
      subtitle: "Famous Italian tenor with big orchestra",
      dates: [
        "SEPTEMBER 23, 2025 — KRASNODAR, RUSSIA",
        "SEPTEMBER 25, 2025 — ESSENTUKI, RUSSIA",
        "SEPTEMBER 29, 2025 — SOCHI, RUSSIA",
        "OCTOBER 02, 2025 — VOLGOGRAD, RUSSIA",
        "NOVEMBER 24, 2025 — KOSTROMA, RUSSIA",
        "NOVEMBER 26, 2025 — PSKOV, RUSSIA",
        "NOVEMBER 28, 2025 — VELIKIY NOVGOROD, RUSSIA",
        "NOVEMBER 30, 2025 — CHEREPOVETS, RUSSIA",
        "DECEMBER 02, 2025 — IVANOVO, RUSSIA",
        "DECEMBER 04, 2025 — VLADIMIR, RUSSIA"
      ]
    },
    {
      id: "paciotti-2024",
      category: "paciotti",
      title: "FEDERICO PACIOTTI",
      subtitle: "Italian ambitious tenor and virtuoso guitarist",
      dates: ["OCTOBER 26, 2024 — KALININGRAD, RUSSIA"]
    },
    {
      id: "turner-2024",
      category: "turner",
      title: "JOE LYNN TURNER",
      subtitle: "American singer known for his work in the hard rock bands Rainbow, Yngwie Malmsteen and Deep Purple",
      dates: [
        "OCTOBER 24, 2024 — MOSCOW, RUSSIA",
        "OCTOBER 26, 2024 — EKATERINBURG, RUSSIA"
      ]
    }
  ],
  source: {
    name: "Official BEST SOUND website",
    url: "https://sound-agency.ru/"
  }
};
